# Tensor tutorial
[Reference](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
#from __future__ import print_function
import torch

## Create an unitialized 5x3 matrix

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[4.7393e+30, 9.5461e-01, 4.4377e+27],
        [1.7975e+19, 4.6894e+27, 7.9463e+08],
        [3.2604e-12, 1.7743e+28, 2.0535e-19],
        [5.9682e-02, 7.0374e+22, 3.8946e+21],
        [4.4650e+30, 7.0975e+22, 7.9309e+34]])


## Create a randomly initialized 5x3 matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3285, 0.5721, 0.1428],
        [0.1060, 0.0123, 0.2390],
        [0.1910, 0.4039, 0.1717],
        [0.2139, 0.7112, 0.3587],
        [0.4969, 0.3824, 0.0272]])


## Create a zero-filled 5x3 matrix

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## Create a tensor out of existing data

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


## Create a 5x3 matrix of ones, with type double float

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Create a randomly initialized matrix out of existing data with type float

In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.4285,  0.5676,  1.2429],
        [ 1.4687, -0.9036, -0.4999],
        [ 0.4819, -1.8172, -1.9265],
        [-1.0395,  0.5230, -0.2102],
        [-0.7817,  0.5936, -2.6942]])


## Get its size

In [8]:
print(x.size())

torch.Size([5, 3])


# Operations

## Addition

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8197,  1.1122,  1.7393],
        [ 2.0162, -0.2137,  0.1116],
        [ 1.4377, -0.9194, -1.5762],
        [-0.4264,  1.4592,  0.4778],
        [-0.3448,  1.2815, -2.2626]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8197,  1.1122,  1.7393],
        [ 2.0162, -0.2137,  0.1116],
        [ 1.4377, -0.9194, -1.5762],
        [-0.4264,  1.4592,  0.4778],
        [-0.3448,  1.2815, -2.2626]])


Any operation that mutates a tensor in-place is postfixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [11]:
y.add_(x)
print(y)

tensor([[ 0.8197,  1.1122,  1.7393],
        [ 2.0162, -0.2137,  0.1116],
        [ 1.4377, -0.9194, -1.5762],
        [-0.4264,  1.4592,  0.4778],
        [-0.3448,  1.2815, -2.2626]])


## Numpy indexing

In [12]:
print(x[:, 1])

tensor([ 0.5676, -0.9036, -1.8172,  0.5230,  0.5936])


## Resizing: `torch.view`

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Getting python numbers: `.item()`

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4045])
-0.4045192301273346


**Read later:**
100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html)

# Numpy bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

## Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensors can be moved onto any device using the `.to` method.

In [18]:
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('CUDA device not available')

CUDA device not available
